name: Windows RDP Ngrok

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Mengaktifkan RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Buat Password User Administrator
      run: |
        $Password = ConvertTo-SecureString "Rahasia123!" -AsPlainText -Force
        New-LocalUser "RDPUser" -Password $Password -FullName "RDP User" -Description "User RDP"
        Add-LocalGroupMember -Group "Administrators" -Member "RDPUser"

    - name: Unduh & Install Ngrok
      run: |
        choco install ngrok -y

    - name: Konfigurasi & Jalankan Ngrok
      run: |
        ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        Start-Process ngrok -ArgumentList "tcp 3389 --log=stdout" -NoNewWindow

    - name: Tampilkan Alamat Koneksi RDP
      run: |
        $maxRetries = 15
        $retryCount = 0
        $tunnel = $null
        while ($retryCount -lt $maxRetries -and $tunnel -eq $null) {
          Start-Sleep -Seconds 3
          try {
            $tunnel = Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels -ErrorAction Stop
          } catch {
            $retryCount++
          }
        }
        if ($tunnel -and $tunnel.tunnels.Length -gt 0) {
          $public_url = $tunnel.tunnels[0].public_url
          Write-Host "=========================================="
          Write-Host "ALAMAT KONEKSI RDP: $public_url"
          Write-Host "USERNAME        : RDPUser"
          Write-Host "PASSWORD        : Rahasia123!"
          Write-Host "=========================================="
        } else {
          Write-Host "Error: Ngrok tidak merespons atau Authtoken salah."
          exit 1
        }

    - name: Menjaga RDP Tetap Aktif
      run: |
        $i = 0
        while ($i -lt 360) {
          Start-Sleep -Seconds 60
          $i++
        }
